### ISSUE TITLE
Do you apply data augmentation?

### ISSUE THREAD

**Issue by doantientai** [zhaohengyuan1/Color2Embed#3]
Hi @zhaohengyuan1 and the team,

Congratulations on the great work! Well done! :smile: 

Just a small question. Do you think it would be a good idea to apply data augmentations on images during the training? I guess the model would be even more robust. And if I want to do it, do you have any advice on how, and where should I do it in your source?

Thank you very much and have a nice day!

**Comment by doantientai** [comment]
Oh, I think I found it. You already applied them here: [https://github.com/zhaohengyuan1/Color2Embed/blob/main/train.py#L327](https://github.com/zhaohengyuan1/Color2Embed/blob/main/train.py#L327)

**Comment by zhaohengyuan1** [comment]
ok
